CREATE TABLE IF NOT EXISTS IDP_BASE_TABLE (
            NAME VARCHAR (20),
            PRIMARY KEY (NAME)
);

INSERT INTO IDP_BASE_TABLE values ('IdP');

CREATE TABLE IF NOT EXISTS UM_TENANT_IDP (
			UM_ID INTEGER AUTO_INCREMENT,
			UM_TENANT_ID INTEGER,
			UM_TENANT_IDP_NAME VARCHAR(254),
			UM_TENANT_IDP_PRIMARY CHAR(1)  NOT NULL,
			UM_TENANT_IDP_HOME_REALM_ID VARCHAR(254),
			UM_TENANT_IDP_THUMBPRINT VARCHAR(2048),
			UM_TENANT_IDP_TOKEN_EP_ALIAS VARCHAR(254),			
			UM_TENANT_IDP_SAML2_SSO_ENABLED CHAR(1)  NOT NULL,
			UM_TENANT_IDP_ISSUER VARCHAR(512),
			UM_TENANT_IDP_SP_ENTITY_ID VARCHAR(512),
            		UM_TENANT_IDP_URL VARCHAR(2048),	
			UM_TENANT_IDP_AUTHN_REQUEST_SIGNED CHAR(1)  NOT NULL,
			UM_TENANT_IDP_LOGOUT_ENABLED CHAR(1)  NOT NULL,
			UM_TENANT_IDP_LOGOUT_URL VARCHAR(2048),
			UM_TENANT_IDP_LOGOUT_REQUEST_SIGNED CHAR(1)  NOT NULL,
			UM_TENANT_IDP_AUTHN_RESPONSE_SIGNED CHAR(1)  NOT NULL,
			UM_TENANT_IDP_OIDC_ENABLED CHAR(1)  NOT NULL,
			UM_TENANT_IDP_CONSUMER_KEY VARCHAR (512),
            		UM_TENANT_IDP_CONSUMER_SECRET VARCHAR (512),
			UM_TENANT_IDP_AUTHZ_URL VARCHAR(2048),
			UM_TENANT_IDP_TOKEN_URL VARCHAR(2048),	
			PRIMARY KEY (UM_ID),
			UNIQUE (UM_TENANT_ID, UM_TENANT_IDP_NAME));

CREATE TABLE IF NOT EXISTS UM_TENANT_IDP_ROLES (
			UM_ID INTEGER AUTO_INCREMENT,
			UM_TENANT_IDP_ID INTEGER,
			UM_TENANT_IDP_ROLE VARCHAR(254),
			PRIMARY KEY (UM_ID),
			UNIQUE (UM_TENANT_IDP_ID, UM_TENANT_IDP_ROLE),
			FOREIGN KEY (UM_TENANT_IDP_ID) REFERENCES UM_TENANT_IDP(UM_ID) ON DELETE CASCADE);

CREATE TABLE IF NOT EXISTS UM_TENANT_IDP_ROLE_MAPPINGS (
			UM_ID INTEGER AUTO_INCREMENT,
			UM_TENANT_IDP_ROLE_ID INTEGER,
			UM_TENANT_ID INTEGER,
			UM_TENANT_ROLE VARCHAR(253),	
			PRIMARY KEY (UM_ID),
			UNIQUE (UM_TENANT_IDP_ROLE_ID, UM_TENANT_ID, UM_TENANT_ROLE),
			FOREIGN KEY (UM_TENANT_IDP_ROLE_ID) REFERENCES UM_TENANT_IDP_ROLES(UM_ID) ON DELETE CASCADE);

CREATE TABLE IF NOT EXISTS UM_TENANT_IDP_CLAIMS (
			UM_ID INTEGER AUTO_INCREMENT,
			UM_TENANT_IDP_ID INTEGER,
			UM_TENANT_IDP_CLAIM VARCHAR(254),
			PRIMARY KEY (UM_ID),
			UNIQUE (UM_TENANT_IDP_ID, UM_TENANT_IDP_CLAIM),
			FOREIGN KEY (UM_TENANT_IDP_ID) REFERENCES UM_TENANT_IDP(UM_ID) ON DELETE CASCADE);

CREATE TABLE IF NOT EXISTS UM_TENANT_IDP_CLAIM_MAPPINGS (
			UM_ID INTEGER AUTO_INCREMENT,
			UM_TENANT_IDP_CLAIM_ID INTEGER,
			UM_TENANT_ID INTEGER,
			UM_TENANT_CLAIM VARCHAR(253),	
			PRIMARY KEY (UM_ID),
			UNIQUE (UM_TENANT_IDP_CLAIM_ID, UM_TENANT_ID, UM_TENANT_CLAIM),
			FOREIGN KEY (UM_TENANT_IDP_CLAIM_ID) REFERENCES UM_TENANT_IDP_CLAIMS(UM_ID) ON DELETE CASCADE);
